---
services:
  webtop:
    image: ghcr.io/akiitr/webtop:latest
    container_name: webtop
    privileged: true # Provides full root privileges on the host, including access to devices. This is the highest level of privilege.
    security_opt:
      - seccomp:unconfined # As recommended by the docs for modern GUI apps to prevent syscall-related crashes.
    environment:
      - PUID=1000 # Your user ID
      - PGID=1000 # Your group ID
      - TZ=Asia/Kolkata  # Your timezone
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
      - START_DOCKER=false # We are mounting the host's docker socket, so we don't need Docker-in-Docker.
    volumes:
      # This is the most important part. Change this to a real path on your host machine.
      - /home/anubhavk/webtop/tmp:/config
      - /home/anubhavk/:/config/anubhavk
      - /mnt/c/Users/anubhavk:/config/c
      # Mount the host's Docker socket to control Docker from within the container.
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 7000:3000
      - 7001:3001
    shm_size: "2gb" # Increased shared memory for better browser and app performance.
    restart: unless-stopped
